/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum2;

/**
 *
 * @author Naya
 */
public class array extends javax.swing.JFrame {
    String jns = "";
    int jml;
    /**
     * Creates new form array
     */
    public array() {
        initComponents();
        getJumlah();
        setJenis();
        panel1.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel1 = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thasil = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 210, 30);

        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 120, 20);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(260, 50, 110, 30);

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setLayout(null);

        ket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.add(ket);
        ket.setBounds(134, 14, 93, 29);

        jLabel6.setText("Jumlah Bilangan");
        panel1.add(jLabel6);
        jLabel6.setBounds(26, 53, 92, 16);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel1.add(pilihanbil);
        pilihanbil.setBounds(136, 50, 179, 22);

        bil1.setText("Bilangan 1");
        panel1.add(bil1);
        bil1.setBounds(26, 82, 59, 16);

        bil2.setText("Bilangan 2");
        panel1.add(bil2);
        bil2.setBounds(26, 111, 59, 16);

        bil3.setText("Bilangan 3");
        panel1.add(bil3);
        bil3.setBounds(26, 140, 59, 16);

        bil4.setText("Bilangan 4");
        panel1.add(bil4);
        bil4.setBounds(26, 169, 59, 16);

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        panel1.add(b1);
        b1.setBounds(134, 79, 181, 22);

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        panel1.add(b2);
        b2.setBounds(134, 108, 181, 22);

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        panel1.add(b3);
        b3.setBounds(134, 137, 181, 22);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        panel1.add(b4);
        b4.setBounds(134, 166, 181, 22);

        button.setText("Hitung");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        panel1.add(button);
        button.setBounds(197, 206, 69, 25);

        thasil.setColumns(20);
        thasil.setRows(5);
        jScrollPane1.setViewportView(thasil);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(134, 238, 181, 96);

        getContentPane().add(panel1);
        panel1.setBounds(30, 110, 340, 348);

        jLabel4.setText("Operasi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 70, 70, 40);

        panel.setBackground(new java.awt.Color(0, 255, 51));
        panel.setLayout(null);
        getContentPane().add(panel);
        panel.setBounds(0, 0, 400, 480);

        setBounds(0, 0, 418, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel1.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel1.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel1.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel1.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        
    }
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        Double hsl =0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml==2){
                hsl = a1+a2;
                thasil.setText(""+a1+"+"+a2+"="+hsl);
            }
            if(jml==3){
                hsl = a1+a2+a3;
                thasil.setText(""+a1+"+"+a2+"+"+a3+"="+hsl);
            }if(jml==4){
                hsl = a1+a2+a3+a4;
                thasil.setText(""+a1+"+"+a2+"+"+a3+"+"+a4+"="+hsl);
            }
            
        }
        else if(jns.equals("Pengurangan")){
            if(jml==2){
                hsl = a1-a2;
                thasil.setText(""+a1+"-"+a2+"="+hsl);
            }
            if(jml==3){
                hsl = a1-a2-a3; 
                thasil.setText(""+a1+"-"+a2+"-"+a3+"="+hsl);
            }if(jml==4){
                hsl = a1-a2-a3-a4; 
                thasil.setText(""+a1+"-"+a2+"-"+a3+"-"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml==2){
                hsl = a1*a2;
                thasil.setText(""+a1+"X"+a2+"="+hsl);
            }
            if(jml==3){
                hsl = a1*a2*a3; 
                thasil.setText(""+a1+"X"+a2+"X"+a3+"="+hsl);
            }if(jml==4){
                hsl = a1*a2*a3*a4; 
                thasil.setText(""+a1+"X"+a2+"X"+a3+"X"+a4+"="+hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml==2){
                hsl = a1/a2;
                thasil.setText(""+a1+":"+a2+"="+hsl);
            }
            if(jml==3){
                hsl = a1/a2/a3; 
                thasil.setText(""+a1+":"+a2+":"+a3+"="+hsl);
            }if(jml==4){
                hsl = a1/a2/a3/a4; 
                thasil.setText(""+a1+":"+a2+":"+a3+":"+a4+"="+hsl);
            }
        }
        
    }//GEN-LAST:event_buttonActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
    getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
public void getJumlah() {
        if(pilihanbil.getSelectedItem().equals("2")){
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 2;
    }
        else if(pilihanbil.getSelectedItem().equals("3")){
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 3;
    }
        if(pilihanbil.getSelectedItem().equals("4")){
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        bil1.setVisible(true);
        bil2.setVisible(true);
        b1.setVisible(true);
        b2.setVisible(true);
        jml = 4;
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new array().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JButton button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextArea thasil;
    // End of variables declaration//GEN-END:variables

    

    
}
